# SwiftLint Configuration for Brixie
# https://github.com/realm/SwiftLint

# Paths to include/exclude
included:
  - Brixie
  - BrixieTests
  - BrixieUITests

excluded:
  - Pods
  - .build
  - build
  - DerivedData
  - vendor

# Rules configuration
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

disabled_rules:
  - todo  # Allow TODO comments during development

# Rule customization
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - db
    - ui

type_name:
  min_length:
    warning: 3
    error: 3
  max_length:
    warning: 40
    error: 50

# Custom rules
custom_rules:
  # Encourage use of SwiftUI over UIKit where appropriate
  avoid_uikit_in_swiftui:
    name: "Avoid UIKit in SwiftUI"
    regex: "import UIKit.*\n.*struct.*View"
    message: "Consider using SwiftUI alternatives instead of UIKit"
    severity: warning
    
  # Ensure proper file headers
  file_header:
    required_pattern: |
                      \/\/
                      \/\/.*\.swift
                      \/\/.*Brixie.*
                      \/\/
                      \/\/.*Created by.*
                      \/\/