blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/mpwg/brixie-ios/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/mpwg/brixie-ios/wiki
    about: Check out the project documentation and guides
