name: 📋 General Issue
description: Create a general issue for anything that doesn't fit other categories
title: "[ISSUE] "
labels: ["needs-triage"]
assignees:
  - mpwg

body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating an issue! Please provide as much detail as possible.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Question
        - Documentation
        - Performance
        - Accessibility
        - Build/CI Issues
        - Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant information
      placeholder: Any additional information that might be helpful

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this issue?
      options:
        - Low
        - Medium
        - High
        - Critical