name: Code Quality

permissions:
  contents: read
  pull-requests: write
  checks: write

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  swiftlint:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./Brixie
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SwiftLint
        run: |
          brew install swiftlint

      - name: SwiftLint Version
        run: swiftlint version

      - name: Run SwiftLint
        run: |
          swiftlint lint --reporter github-actions-logging

      - name: Run SwiftLint (Strict)
        if: github.event_name == 'pull_request'
        run: |
          swiftlint lint --strict --reporter checkstyle > swiftlint-results.xml
        continue-on-error: true

      - name: Upload SwiftLint Results
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: swiftlint-results
          path: ./Brixie/swiftlint-results.xml
          retention-days: 7

  swift-format:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./Brixie
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Swift Format
        run: |
          # Install swift-format via Swift Package Manager
          git clone https://github.com/apple/swift-format.git /tmp/swift-format
          cd /tmp/swift-format
          swift build -c release
          sudo cp .build/release/swift-format /usr/local/bin/swift-format

      - name: Check Swift Format
        run: |
          swift-format lint --recursive . || echo "⚠️ Format issues found"

  build-analysis:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./Brixie
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Analyze Build
        run: |
          xcodebuild analyze -project Brixie.xcodeproj -scheme Brixie \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
            | tee build-analysis.log

      - name: Upload Analysis Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-analysis
          path: ./Brixie/build-analysis.log
          retention-days: 7
