name: iOS CI

permissions:
  contents: read

on:
  push:
    branches: [main, docs/*]
  pull_request:
    branches: [main]

jobs:
  ios-build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./Brixie
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: Setup Ruby (for CocoaPods if needed)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Cache CocoaPods
        if: hashFiles('**/Podfile.lock') != ''
        uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Cache Swift Package Manager
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/SourcePackages
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Install CocoaPods Dependencies
        if: hashFiles('**/Podfile') != ''
        run: |
          gem install cocoapods
          pod install --repo-update

      - name: Build iOS App
        run: |
          echo "🔨 Building iOS App..."
          if xcodebuild -project Brixie.xcodeproj -scheme Brixie \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
            build; then
            echo "✅ Build completed successfully"
          else
            echo "❌ Build failed"
            exit 1
          fi

      - name: Run Unit Tests
        run: |
          echo "🧪 Running Unit Tests..."
          if xcodebuild test -project Brixie.xcodeproj -scheme Brixie \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=latest"; then
            echo "✅ Unit tests passed"
          else
            echo "❌ Unit tests failed"
            exit 1
          fi

      - name: Run UI Tests
        run: |
          echo "🖥️ Running UI Tests..."
          if xcodebuild test -project Brixie.xcodeproj -scheme Brixie \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=latest" \
            -only-testing:BrixieUITests; then
            echo "✅ UI tests passed"
          else
            echo "⚠️ UI tests failed or no UI tests found"
          fi
        continue-on-error: true
      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-logs
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/**
          retention-days: 7

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/**
          retention-days: 7

